### ISSUE TITLE
Suggestion: Option to collapse Categories in web app

### ISSUE THREAD

**Issue by AberDerBart** [tstehr/shoppinglist#79]
This feature would enable 
1. hiding items that are not available (after having bought everything else in their category)
2. navigating the list with more ease when you are in a shop you have no order for (e.g. on holiday)

**Comment by tstehr** [comment]
I can see the use case, but I'm having a hard time envisioning this with the current design. Could you sketch an UI for how this might work?

**Comment by AberDerBart** [comment]
Something like this - group the items by category that can expand / collapse by clicking on the botton on the right:
![shop_cat](https://user-images.githubusercontent.com/8435083/146681583-e2685bde-2372-459a-8641-3c763e793bc2.jpg)

**Comment by tstehr** [comment]
This proposed UI has the problem that there's no longer an option to change the category of items, since there's no longe a category indicator to click in front of an item. 

As a general note, since I myself don't have I need for this feature, it'll most likely be some time before I get around to this feature request (if ever). I'm definitely open for PRs in this direction if you want to give it a shot.
